### ISSUE TITLE
xfrpc: can't load library 'libevent-2.1.so.6' and solution

### ISSUE THREAD

**Issue by ferstar** [KunTengRom/xfrp#12]
The libevent2's default version is 2.0.21 on OpenWrt BARRIER BREAKER 14.09 but for xfrpc it requires 2.1.6.
So I have to compile version 2.1.6 to meet xfrpc's need, and finally it works.
Here is my solution: https://github.com/ferstar/openwrt-libevent21
ipks for ramips: https://github.com/ferstar/openwrt-libevent21/releases

**Comment by liudf0716** [comment]
@ferstar xfrpc didn't need libevent 2.1.x. why u think it need libevent 2.1.x?

**Comment by ferstar** [comment]
@liudf0716 
I have libevent2 version 2.0.21 installed in my openwrt, but when I was running xfrpc it prompted error message as this issue title said:
> xfrpc: can't load library 'libevent-2.1.so.6'
So I think it depends libevent 2.1.6, I cross-compile libevent 2.1.6 for my route, and it works.
